### ISSUE TITLE
Using iTerm when opening the terminal

### ISSUE THREAD

**Issue by joakin** [eldargab/LT-Opener#1]
Hi!

I've managed to use iTerm as the terminal that opens by adding this behavior in my user.behaviors

``` clojure
:lt.plugins.opener/settings [(:lt.plugins.opener/set-shell-command
                              :terminal
                              :mac
                              ["open" "-a" "iTerm" "{{path}}"]
                               )]
```

It brings the app as if Command-Tab and opens the terminal in a tab in the most active terminal window (which is good enough for me, there is probably ways to pass args to iterm to open splits, etc).

You may want to add this to the readme since it is a fairly used Terminal alternative.

Thanks for the plugin, it is great.

**Comment by eldargab** [comment]
I'll add it, thanks!
