### ISSUE TITLE
Not updating?

### ISSUE THREAD

**Issue by spelufo** [eldargab/LT-Opener#3]
I don't know how plugin updating works, or if it should keep up to date with github directly, but in any case, I am not getting the version of `opener.behaviors` with the linux setting added. I added them manually, but perhaps you should republish the plugin?

Also, should't linux's reveal and open be swaped? I guess what you want is reveal to show a file in a file browser and open to open the file with the default application. Do I have it backwards?

**Comment by eldargab** [comment]
Right, the linux commands should be swapped. I'll try to release everything tomorrow.

**Comment by eldargab** [comment]
Done!
