### ISSUE TITLE
Behaviors file isn't in the new format

### ISSUE THREAD

**Issue by kenny-evitt** [eldargab/LT-Opener#5]
This is in reference to [this comment](https://github.com/LightTable/LightTable/issues/533#issuecomment-154682886) reporting that the plugin doesn't seem to be working (for the 0.8.0 alpha release I believe).

[Here's the commit in the core LT repo that changed the format.](https://github.com/LightTable/LightTable/commit/ecc0fd49d744ad29369cf531a5f622405511507d) This change has been in all LT versions since 0.7.0.

[Here's an example of the same change for the behaviors file for the default HTML plugin behaviors file.](https://github.com/LightTable/HTML/commit/69c635e2a265275dd98f85fa180c84bf05b7fa81)

**Comment by eldargab** [comment]
To my knowledge LT still supports the old format. Shouldn't be an issue. We can reopen if someone confirms the problem.

**Comment by kenny-evitt** [comment]
@eldargab It's definitely not an issue. I just installed the plugin and was able to use the "Open Terminal here" command. Sorry for the false alarm and thanks for teaching me something new.
